-- 코드를 입력하세요
SELECT YEAR
     , MONTH
     , GENDER
     , COUNT(DISTINCT USERS) AS USERS
FROM (SELECT EXTRACT(YEAR FROM B.SALES_DATE) AS YEAR
           , EXTRACT(MONTH FROM B.SALES_DATE) AS MONTH
           , A.GENDER
           , A.USER_ID AS USERS
      FROM USER_INFO A
         , ONLINE_SALE B
      WHERE A.USER_ID = B.USER_ID
      AND A.GENDER IS NOT NULL)
GROUP BY YEAR
       , MONTH
       , GENDER
ORDER BY YEAR
       , MONTH
       , GENDER