-- 코드를 입력하세요

 SELECT EXTRACT(YEAR FROM B.SALES_DATE) AS YEAR
      , EXTRACT(MONTH FROM B.SALES_DATE) AS MONTH
      , COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS
      , ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(USER_ID) 
                                           FROM USER_INFO
                                           WHERE EXTRACT(YEAR FROM JOINED) = '2021'), 1) AS PUCHASED_RATIO
 FROM USER_INFO A
    , ONLINE_SALE B
 WHERE A.USER_ID = B.USER_ID
 AND EXTRACT(YEAR FROM A.JOINED) = '2021'
 GROUP BY EXTRACT(YEAR FROM B.SALES_DATE)
        , EXTRACT(MONTH FROM B.SALES_DATE)
 ORDER BY MONTH