-- 코드를 입력하세요
SELECT B.HOUR 
      , NVL(A.COUNT,0) as COUNT  
FROM (SELECT TO_CHAR(DATETIME,'HH24') as HOUR
            , COUNT(*) as COUNT
      FROM ANIMAL_OUTS
      GROUP BY TO_CHAR(DATETIME,'HH24')
      ORDER BY 1) A
    ,(SELECT LEVEL-1 AS HOUR 
      FROM DUAL
      CONNECT BY LEVEL <=24) B
WHERE A.HOUR(+) = B.HOUR
ORDER BY 1 ASC;