-- 코드를 입력하세요   

SELECT A.PRODUCT_CODE
    , (SUM(B.SALES_AMOUNT) * A.PRICE) AS AA
FROM PRODUCT A
    , OFFLINE_SALE B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY AA DESC, A.PRODUCT_CODE ASC;
